### PR TITLE
Basic end-to-end tests for Chime [WIP]

### LINKED ISSUE #180: Super basic CI for Chime

### PR DESCRIPTION
**Pull request by bsmithgall**
### What Changed
+ Added series of [fabric]() commands for creating new AWS instance, starting an instance of Chime in AWS, destroying AWS instance
+ Added [selenium]() test to visit & login to Chime, create a test page, and preview it.

### Issues
+ Fixes #180 (Super basic CI for Chime)

### TODO/Open questions
+ Is the way that the hosts are managed right now smart (Writing the public dns to a `hosts.txt` file)?
+ Is there a way to do this in a more automated way? Right now, this requires someone to run `fab test_chime` from their machine.
+ Are there other Selenium tests that should be included?
+ There are some hard dependencies here (Firefox, for example). Do we care about testing cross-browser? Or is that beyond scope here?
+ What docs should be written/modified to talk about these changes?

### Screencap
autom8

### CODE REVIEW

**Comment by bsmithgall** [comment]
With the latest commit, you should be able to pull down this branch and just run `fab test_chime` and have everything work as expected. The whole process takes around 15 minutes from new instance to tear down.

**Comment by wpietri** [comment]
Yay! This is exciting. Is there some setup needed? My result:

```
william@chandler:/tmp/ceviche-cms$ fab test_chime
Connecting to EC2...
Booting up instance...
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/usr/lib/python2.7/dist-packages/fabric/tasks.py", line 405, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/usr/lib/python2.7/dist-packages/fabric/tasks.py", line 171, in run
    return self.wrapped(*args, **kwargs)
  File "/tmp/ceviche-cms/fabfile/tasks.py", line 88, in test_chime
    public_dns = _create_ec2_instance()
  File "/tmp/ceviche-cms/fabfile/tasks.py", line 157, in _create_ec2_instance
    instance_type=fabconf.get('EC2_INSTANCE_TYPE')
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/image.py", line 325, in run
    tenancy=tenancy, dry_run=dry_run)
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 961, in run_instances
    verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1178, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidGroup.NotFound</Code><Message>The security group 'none' does not exist</Message></Error></Errors><RequestID>61682d61-7383-4900-ba08-4452484b05ed</RequestID></Response>

```

**Comment by bsmithgall** [comment]
Yeah there are a bunch of environmental variables you need to set:

```
export AWS_ACCESS_KEY=<your aws access key id>
export AWS_SECRET_KEY=<your aws secret>
export TESTING_EMAIL=<your persona login (email)>
export TESTING_PASSWORD=<your persona login (password)>
export EC2_KEY_PAIR='cfa-chime-keypair'
export AWS_SECURITY_GROUPS="default"
```

**Comment by bsmithgall** [comment]
Anything else that is needed for this? Happy to go through any remaining puzzling bits in person.

**Pull request merged**
